### ISSUE TITLE
Add a close button to the solution types modal dialog - feat0032

### ISSUE THREAD

**Issue by slugbucket** [slugbucket/crossword-hints#33]
Add a close button to the modal dialog on the solutions form similar to what is shown at https://www.w3schools.com/Bootstrap/bootstrap_ref_js_modal.asp.
Note that the ESC key doesn't work to exit the dialog.

**Comment by slugbucket** [comment]
Based on https://www.w3schools.com/howto/howto_css_modals.asp add a form element

```html
<div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
```
with appropriate styling,
```css
/* Modal Footer */
.modal-footer {
  padding: 2px 16px;
  background-color: #5cb85c;
  color: white;
}
```
